import { prisma } from '../prisma';
import { createUrl } from '../../src/lib/utils';

const categories = [
  {
    name: 'FM модулятори',
    id: 1,
    departmentId: 1,
    image: '',
  },
  {
    name: 'Автомобільні тримачі',
    id: 2,
    departmentId: 1,
    image: '',
  },
  {
    name: 'Інші аксесуари',
    id: 3,
    departmentId: 1,
    image: '',
  },
  {
    name: 'Тримачі телефонів і смартфонів PopSockets',
    id: 4,
    departmentId: 2,
    image: '',
  },
  {
    name: 'Акумулятори',
    id: 5,
    departmentId: 1,
    image: '',
  },
  {
    name: 'Кабелі та перехідники',
    id: 6,
    departmentId: 2,
    image: '',
  },
  {
    name: 'Повербанки та зарядні станції',
    id: 7,
    departmentId: 2,
    image: '',
  },
  {
    name: 'Зарядні пристрої та перехідники',
    id: 8,
    departmentId: 2,
    image: '',
  },
  {
    name: 'Акустичні системи',
    id: 9,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Кишені і док-станції для жорстких дисків ',
    id: 10,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Миші і маніпулятори',
    id: 11,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Навушники та гарнітура',
    id: 12,
    departmentId: 2,
    image: '',
  },
  {
    name: 'Смарт-годинники та фітнес-трекери',
    id: 13,
    departmentId: 5,
    image: '',
  },
  {
    name: 'Акумулятори та батарейки ',
    id: 14,
    departmentId: 5,
    image: '',
  },
  {
    name: 'USB Тестери',
    id: 15,
    departmentId: 6,
    image: '',
  },
  {
    name: 'Захисні плівки та скло ',
    id: 16,
    departmentId: 2,
    image: '',
  },
  {
    name: 'Камери та відеоспостереження',
    id: 17,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Настільні лампи та ліхтарики',
    id: 18,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Роутери та аксесуари',
    id: 19,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Клавіатури та аксесуари',
    id: 20,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Вентилятори',
    id: 21,
    departmentId: 4,
    image: '',
  },
  {
    name: "Флеш накопичувачі, карти пам'яті та кард-рідери",
    id: 22,
    departmentId: 2,
    image: '',
  },
  {
    name: 'Килимки та робочі поверхні',
    id: 23,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Кабелі та адаптери',
    id: 24,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Корпуси та задні кришки',
    id: 25,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Чохли та накладки',
    id: 26,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Клей та розчинники',
    id: 27,
    departmentId: 7,
    image: '',
  },
  {
    name: 'OCA-плівки',
    id: 28,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Підсвічування та поляризаційні плівки',
    id: 29,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Дисплейні рамки',
    id: 30,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Скло для дисплею та камер',
    id: 31,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Проклейки та прокладки',
    id: 32,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Динаміки',
    id: 33,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Дисплеї та дисплейні модулі',
    id: 34,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Камери',
    id: 35,
    departmentId: 3,
    image: '',
  },
  {
    name: "Конектори та роз'єми",
    id: 36,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Мікросхеми',
    id: 37,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Мікрофони',
    id: 38,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Гвинти',
    id: 39,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Сенсори та сенсорні панелі',
    id: 40,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Шлейфи',
    id: 41,
    departmentId: 3,
    image: '',
  },
  {
    name: 'Жорсткі диски та дискові масиви ',
    id: 42,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Акумулятори для ноутбуків',
    id: 43,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Дисплеї та матриці',
    id: 44,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Зарядні пристрої для ноутбуків',
    id: 45,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Адаптери живлення для моніторів',
    id: 46,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Підставки та охолоджуючі поверхні',
    id: 47,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Клавіатури для ноутбуків',
    id: 48,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Шлейфи для ноутбуків',
    id: 49,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Блоки живлення',
    id: 50,
    departmentId: 6,
    image: '',
  },
  {
    name: 'Вакуумні ламінатори та автоклави',
    id: 51,
    departmentId: 6,
    image: '',
  },
  {
    name: 'Викрутки',
    id: 52,
    departmentId: 6,
    image: '',
  },
  {
    name: 'Бормашини',
    id: 53,
    departmentId: 6,
    image: '',
  },
  {
    name: 'Розхідні матеріали',
    id: 54,
    departmentId: 6,
    image: '',
  },
  {
    name: 'Тестери АКБ',
    id: 55,
    departmentId: 6,
    image: '',
  },
  {
    name: 'Інший інструмент',
    id: 56,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Кусачки та пасатижі',
    id: 57,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Лак ізоляційний та струмопровідний',
    id: 58,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Монтажні столи та робочі поверхні',
    id: 59,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Мультіметри',
    id: 60,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Оптичні прилади',
    id: 61,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Паяльні пасти та BGA кульки',
    id: 62,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Паяльні жала',
    id: 63,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Паяльні станції',
    id: 64,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Переднагрівачі',
    id: 65,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Пінцети',
    id: 66,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Припої, флюси для паяння',
    id: 67,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Термопасти та термоінтерфейси',
    id: 68,
    departmentId: 4,
    image: '',
  },
  {
    name: 'Програматори',
    id: 69,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Сепаратори та аксесуари',
    id: 70,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Скальпелі',
    id: 71,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Скотч',
    id: 72,
    departmentId: 7,
    image: '',
  },
  {
    name: 'Трафарети BGA',
    id: 73,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Ультразвукові ванни',
    id: 74,
    departmentId: 8,
    image: '',
  },
  {
    name: 'Обплетення для зняття припою',
    id: 75,
    departmentId: 7,
    image: '',
  },
];

export async function createCategories() {
  for (const category of categories) {
    await prisma.category.create({
      data: {
        name: category.name,
        url: createUrl(category.name),
        image: category.image || 'no-image.png',
        department: {
          connect: {
            id: category.departmentId,
          },
        },
      },
    });
  }
}
