import { prisma } from '../prisma';

const categories = [
  {
    id: 1,
    name: 'Шлейфи + антени + підсвічування + коаксіальні кабелі',
    url: 'shlejfi-anteni-pidsvichuvannya-koaksialni-kabeli',
    departmentId: 1,
    image: 'categories/flex-cables-coaxial-cables.png',
  },
  {
    id: 2,
    name: 'Конектори, утримувачі SIM-карт',
    url: 'konektori-utrimuvachi-sim-kart',
    departmentId: 1,
    image: 'categories/charge-connector.png',
  },
  {
    id: 3,
    name: 'Динаміки та дзвінки',
    url: 'dinamiki-ta-dzvinki',
    departmentId: 1,
  },
  { id: 4, name: 'Мікрофони', url: 'mikrofoni', departmentId: 1 },
  {
    id: 5,
    name: 'Дисплеї',
    url: 'displeyi',
    departmentId: 1,
    image: 'categories/lcd.png',
  },
  { id: 6, name: 'Мікросхеми', url: 'mikroshemi', departmentId: 1 },
  {
    id: 7,
    name: 'Скло екрану + Скло камери',
    url: 'sklo-ekranu-sklo-kameri',
    departmentId: 1,
    image: 'categories/replacement-screen.png',
  },
  {
    id: 8,
    name: 'Задні кришки + рамки + середні частини',
    url: 'zadni-krishki-ramki-seredni-chastini',
    departmentId: 1,
  },
  { id: 9, name: 'Сенсорні панелі', url: 'sensorni-paneli', departmentId: 1 },
  {
    id: 10,
    name: 'Поляризаційна плівка, OCA',
    url: 'polyarizatsijna-plivka-oca',
    departmentId: 1,
  },
  { id: 11, name: 'Скотч', url: 'skotch', departmentId: 1 },
  { id: 12, name: 'Інше', url: 'inshe', departmentId: 2 },
  {
    id: 13,
    name: 'Зарядні пристрої',
    url: 'zaryadni-pristroyi',
    departmentId: 2,
  },
  { id: 14, name: 'Навушники', url: 'navushniki', departmentId: 2 },
  {
    id: 15,
    name: 'Акумулятори + Power Bank',
    url: 'akumulyatori-power-bank',
    departmentId: 2,
  },
  {
    id: 16,
    name: 'Bluetooth адаптери',
    url: 'bluetooth-adapteri',
    departmentId: 3,
  },
  {
    id: 17,
    name: 'Кабелі та адаптери',
    url: 'kabeli-ta-adapteri',
    departmentId: 3,
  },
  {
    id: 18,
    name: 'Миші та маніпулятори',
    url: 'mishi-ta-manipulyatori',
    departmentId: 3,
  },
  { id: 19, name: 'Колонки', url: 'kolonki', departmentId: 3 },
  {
    id: 20,
    name: 'Захисне скло + товари для наклеювання захисного скла',
    url: 'zahisne-sklo-tovari-dlya-nakleyuvannya-zahisnogo-skla',
    departmentId: 2,
  },
  {
    id: 21,
    name: 'Кабелі AUX + OTG перехідники + перехідники + Відео перехідники + USB подовжувачі',
    url: 'kabeli-aux-otg-perehidniki-perehidniki-video-perehidniki-usb-podovzhuvachi',
    departmentId: 2,
  },
  { id: 22, name: 'Чохли', url: 'chohli', departmentId: 2 },
  { id: 23, name: 'FM модулятори', url: 'fm-modulyatori', departmentId: 2 },
  {
    id: 24,
    name: 'Тримачі та Кріплення',
    url: 'trimachi-ta-kriplennya',
    departmentId: 2,
  },
  {
    id: 25,
    name: 'Гідрогелеві плівки',
    url: 'gidrogelevi-plivki',
    departmentId: 2,
  },
  {
    id: 26,
    name: 'Лампи та ліхтарики',
    url: 'lampi-ta-lihtariki',
    departmentId: 7,
  },
  { id: 27, name: 'Смарт-годинники', url: 'smart-godinniki', departmentId: 4 },
  {
    id: 28,
    name: 'Флюси для паяння',
    url: 'flyusi-dlya-payannya',
    departmentId: 5,
  },
  {
    id: 29,
    name: 'Припої, пасти, та кульки BGA',
    url: 'pripoyi-pasti-ta-kulki-bga',
    departmentId: 5,
  },
  { id: 30, name: 'Паяльні жала', url: 'payalni-zhala', departmentId: 5 },
  {
    id: 31,
    name: 'Викрутки + Набори інструментів',
    url: 'vikrutki-nabori-instrumentiv',
    departmentId: 5,
  },
  {
    id: 32,
    name: 'Паяльні станції + Комплектуючі',
    url: 'payalni-stantsiyi-komplektuyuchi',
    departmentId: 5,
  },
  { id: 33, name: 'Мультиметри', url: 'multimetri', departmentId: 5 },
  {
    id: 34,
    name: 'Ультразвукові ванни',
    url: 'ultrazvukovi-vanni',
    departmentId: 5,
  },
  {
    id: 35,
    name: 'Двосторонній скотч + Термоскотч',
    url: 'dvostoronnij-skotch-termoskotch',
    departmentId: 5,
  },
  {
    id: 36,
    name: 'Сепаратори + Аксесуари',
    url: 'separatori-aksesuari',
    departmentId: 5,
  },
  {
    id: 37,
    name: 'Лабораторні блоки живлення + Аксесуари',
    url: 'laboratorni-bloki-zhivlennya-aksesuari',
    departmentId: 5,
  },
  {
    id: 38,
    name: 'Мікроскопи, бінокуляри',
    url: 'mikroskopi-binokulyari',
    departmentId: 5,
  },
  {
    id: 39,
    name: 'Тримачі плат та магнітні килимки',
    url: 'trimachi-plat-ta-magnitni-kilimki',
    departmentId: 5,
  },
  { id: 40, name: 'Пінцети', url: 'pintseti', departmentId: 5 },
  {
    id: 41,
    name: 'Аналізатор Акумуляторів, Тестери + Аксесуари',
    url: 'analizator-akumulyatoriv-testeri-aksesuari',
    departmentId: 5,
  },
  {
    id: 42,
    name: 'Килимки силіконові',
    url: 'kilimki-silikonovi',
    departmentId: 5,
  },
  {
    id: 43,
    name: 'Клей, розчинник, спрей, лак',
    url: 'klej-rozchinnik-sprej-lak',
    departmentId: 5,
  },
  { id: 44, name: 'Матриці', url: 'matritsi', departmentId: 6 },
  { id: 45, name: 'АКБ', url: 'akb', departmentId: 6 },
  {
    id: 46,
    name: 'Зарядні пристрої + Аксесуари',
    url: 'zaryadni-pristroyi-aksesuari',
    departmentId: 6,
  },
  {
    id: 47,
    name: 'Блоки живлення для моніторів',
    url: 'bloki-zhivlennya-dlya-monitoriv',
    departmentId: 3,
  },
  {
    id: 48,
    name: 'Клавіатурні модулі',
    url: 'klaviaturni-moduli',
    departmentId: 6,
  },
  { id: 49, name: 'Вентилятори', url: 'ventilyatori', departmentId: 6 },
  {
    id: 50,
    name: 'Корпусні запчастини',
    url: 'korpusni-zapchastini',
    departmentId: 6,
  },
  { id: 51, name: 'Коннектори ЗП', url: 'konnektori-zp', departmentId: 6 },
  { id: 52, name: 'Шлейфи матриць', url: 'shlejfi-matrits', departmentId: 6 },
  {
    id: 53,
    name: 'Наліпки на клавіатуру',
    url: 'nalipki-na-klaviaturu',
    departmentId: 6,
  },
  {
    id: 54,
    name: 'Системи охолодження та обслуговування',
    url: 'sistemi-oholodzhennya-ta-obslugovuvannya',
    departmentId: 3,
  },
  {
    id: 55,
    name: 'Накопичувачі + Аксесуари',
    url: 'nakopichuvachi-aksesuari',
    departmentId: 3,
  },
];

export async function createCategories() {
  for (const category of categories) {
    await prisma.category.create({
      data: {
        name: category.name,
        url: category.url,
        image: category.image || 'no-image.png',
        department: {
          connect: {
            id: category.departmentId,
          },
        },
      },
    });
  }
}
