import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { MainHeader, TopHeader } from '@/widgets/Header';
import { Footer } from '@/widgets/Footer';
import HolyLoader from 'holy-loader';
import './globals.css';

const inter = Inter({
  subsets: ['cyrillic'],
});

export const metadata: Metadata = {
  title: 'Remparts - Запчастини, аксесуари для мобільних телефонів та ремонт',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/favicon.ico' }, { url: '/icon.png', type: 'image/png' }],
    apple: ['/apple-icon.png'],
  },
};

// 15.2.4

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="uk-UA"
      className="h-full"
    >
      <body className={`${inter.className} flex min-h-full flex-col antialiased`}>
        <HolyLoader color="rgba(43,94,122,0.6)" />
        <TopHeader />
        <MainHeader className="sticky top-0 z-10 md:static" />
        <main
          className="flex-1"
          id="main"
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
