import { EMAIL, PHONE_NUMBER } from './constants';
import {
  DOMAIN,
  DEPARTMENT_API,
  CATEGORY_API,
  BANNER_API,
  SEARCH_API,
  ALL_USERS,
  RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY,
  AUTH_JWT_SIGNUP_API,
  AUTH_JWT_SIGNIN_API,
  AUTH_JWT_REFRESH_API,
  AUTH_JWT_SIGNOUT_API,
} from './env.constants';

export {
  EMAIL,
  PHONE_NUMBER,
  DOMAIN,
  DEPARTMENT_API,
  CATEGORY_API,
  BANNER_API,
  SEARCH_API,
  ALL_USERS,
  RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY,
  AUTH_JWT_SIGNUP_API,
  AUTH_JWT_SIGNIN_API,
  AUTH_JWT_REFRESH_API,
  AUTH_JWT_SIGNOUT_API,
};
